#! /usr/bin/dh-exec
#[!sparc64] etc/pam.d/weston-remote-access
usr/bin/wcap-decode
usr/bin/weston
usr/bin/weston-*
usr/lib/*/weston/desktop-shell.so
usr/lib/*/weston/fullscreen-shell.so
usr/lib/*/weston/hmi-controller.so
usr/lib/*/weston/ivi-shell.so
usr/lib/*/weston/kiosk-shell.so
usr/lib/*/weston/libexec_weston.so*
usr/lib/*/weston/screen-share.so
usr/lib/*/weston/systemd-notify.so
usr/libexec/weston-desktop-shell
usr/libexec/weston-ivi-shell-user-interface
usr/libexec/weston-keyboard
usr/libexec/weston-simple-im
usr/share/wayland-sessions/weston.desktop
usr/share/weston
